FROM philipsahli/centos-v2:latest

RUN yum install -y postgresql-devel python-virtualenv libevent-devel gcc libffi-devel openssl-devel sudo

RUN useradd -m -d /home/tumbo -s /bin/bash tumbo

WORKDIR /home/tumbo
RUN mkdir /home/tumbo/code/ && chown tumbo:tumbo code

RUN echo cachebust_1401424855

RUN mkdir /home/tumbo/.virtualenvs

RUN virtualenv --no-site-packages /home/tumbo/.virtualenvs/tumbo

RUN echo "tumbo ALL = NOPASSWD: /usr/bin/yum" >> /etc/sudoers

ADD worker /home/tumbo/code/app
ADD tumbo/core /home/tumbo/code/app/core

RUN /home/tumbo/.virtualenvs/tumbo/bin/pip install j2cli sh && /home/tumbo/.virtualenvs/tumbo/bin/pip install -r /home/tumbo/code/app/requirements.txt

CMD ["/bin/bash"]
