apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: tumbo-certificate
  namespace: {{ NAMESPACE }}
spec:
  acme:
    config:
    - domains:
      - {{ FRONTEND_HOST }}
      http01:
        ingress: ""
        ingressClass: nginx
  dnsNames:
  - {{ FRONTEND_HOST }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: tumbo-secret
