apiVersion: v1
kind: List
items:
-   apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: rp-ingress
      #namespace: kube-system
      namespace: tumbo
      annotations:
         nginx.org/ssl-services: "rp-ssl"
    spec:
      tls:
      - hosts:
        - {{ FRONTEND_HOST }}
        secretName: tumbo-secret
      rules:
      - host: {{ FRONTEND_HOST }}
        http:
          paths:
          - path: /
            backend:
              serviceName: rp
              servicePort: 80
          - path: /ssl
            backend:
              serviceName: rp-ssl
              servicePort: 443
